name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build
      run: echo ${{ github.sha }} > Release.txt

    - name: Test
      run: cat Release.txt

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            Release.txt
            LICENSE
